export default {
    clienttimezone: '.gg-login-page',
    loginForm: '.gg-login-form',
    infConnections: '.gg-login-form-title1',
    infoWelcome: '.gg-login-form-title2',
    infoConnectPeople: '.gg-login-form-title3',
    infoWhatYouMayQualifyFor: '.gg-login-form-title1',
    infoTryScreener: '.gg-links-text',
    labelTextForUser: '.gg-label-text',
    labelTextForPass: '.gg-label-text',
    usernameField: '#Username', 
    usernameFieldIcon:'.gg-form-input-icon',    
    passwordField:'#Password',
    passwordFieldIcon:'.gg-form-input-icon',
    btnLogin: '.gg-btn',
    forgotLink: '.gg-links-text',
    forgotUsername: 'a[href*="ForgotUsername"]',
    forgotPassword: 'a[href*="ForgotPassword"]',
    btnReminderUsername: '.gg-link',
    infoifYouNeed: '.gg-login-form-title4',
    infoLearnMore: '.gg-login-form-title4',

    btnGroup: '.gg-btn-group',
    backToLoginBtn: '.gg-btn-group button',
    iForgotMyPasswordLink: 'a[href*="IforgotmyPassword"]',
    iForgotMyUserNameLink: 'a[href*="IforgotmyUserName"]',

    errorTextFieldEmpty: '.gg-error-block li',
    errorIconIsDisplayed: '.gg-error-icon'
}